version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sync_fin_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
